### ISSUE TITLE
DMS

### ISSUE THREAD

**Issue by Toon-cloud** [NCAR/CARMA_dev#18]
DMS is a significant sulfur source.  A large fraction of it goes to methane sulfuric acid.  There is also a possible H2S source.
I think you have to include these as a sulfate source.  I don't see how the model can track it except on emission.

**Comment by tilmes** [comment]
@Toon-cloud in the model we have this sulfur chemistry:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/22222754/215656307-3467ab9a-ac08-47b0-ae0b-ad582ae4ee25.png">
H2S is not in the model.  Since all the DMS goes into SO, SO2, SO3 or H2SO4, for the sulfate budget, don't we need to only keep track of how much H2SO4 (gas) goes into the aerosols?
